### ISSUE TITLE
[Bug] ModuleNotFoundError: No module named 'packaging'

### ISSUE THREAD

**Issue by Ki-er** [Falyrion/Loot-Bot#1]
```
Traceback (most recent call last):
  File "//discord_bot.py", line 4, in <module>
    from bot_modules import get_twitch_data, get_epic_games_data
  File "/bot_modules/get_twitch_data.py", line 4, in <module>
    from webdriver_manager.chrome import ChromeDriverManager
  File "/usr/local/lib/python3.10/site-packages/webdriver_manager/chrome.py", line 7, in <module>
    from webdriver_manager.drivers.chrome import ChromeDriver
  File "/usr/local/lib/python3.10/site-packages/webdriver_manager/drivers/chrome.py", line 1, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
```

When running the bot in Docker, the above error message appears

**Comment by Falyrion** [comment]
Maintenance of this project is currently on halt. Many web scraping methods might no longer work due to changes in the target websites. Furthermore, discord.py is no longer maintained by its developers, therefor a rewrite of this project using pycord would be necessary.
