### ISSUE TITLE
Running docker build -t twitch_prime_bot . gives error

### ISSUE THREAD

**Issue by StefanoCastro** [Falyrion/Loot-Bot#3]
This is the first time I'm using docker, I installed it with this guide: https://www.simplilearn.com/tutorials/docker-tutorial/how-to-install-docker-on-ubuntu

After doing the docker build command I get this error:

```
ubuntu@instance-20221115-1321:~/Loot-Bot-main$ sudo docker build -t twitch_prime_bot .
Sending build context to Docker daemon  324.1kB
Step 1/13 : FROM --platform=linux/amd64 python:3.10
 ---> 13ad26b9696b
Step 2/13 : RUN apt-get -y update
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in 8201d6b20e6f
exec /bin/sh: exec format error
The command '/bin/sh -c apt-get -y update' returned a non-zero code: 1
```

**Comment by StefanoCastro** [comment]
Extra:
I'm also comfortable with running the bot outside of docker within ubuntu but I'm unsure how (sorry pretty newb at this)

**Comment by StefanoCastro** [comment]
Oke I think I fixed it (or on my way to fix it)
Changed the platform to alpine and changed to apt-get commands to the proper apk / apk add commands needs for alpine.

```
FROM --platform=linux/arm64 alpine

RUN apk update
RUN apk add wget

# Install chrome
RUN wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN apk add chromium

COPY ./bot .

# Install python packages
RUN apk add bs4
RUN pip install selenium
RUN pip install discord
RUN pip install pyyaml
RUN pip install webdriver-manager

USER root

# Run bot
CMD python discord_bot.py
```

**Comment by StefanoCastro** [comment]
Oke I think I fixed it (or on my way to fix it)
Changed the platform to alpine and changed to apt-get commands to the proper apk / apk add commands needs for alpine.
Added RUN apk add py-pip and changed Google Chrome to Chromium

```
FROM --platform=linux/arm64 alpine

RUN apk update
RUN apk add wget
RUN apk add py-pip

# Install chrome
RUN wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN apk add chromium

COPY ./bot .

# Install python packages
RUN pip install bs4
RUN pip install selenium
RUN pip install discord
RUN pip install pyyaml
RUN pip install webdriver-manager

USER root

# Run bot
CMD python discord_bot.py
```

**Comment by StefanoCastro** [comment]
Mmm, the bot runs, but it seems changing to chromium didn't do any good
Trying the !twitch commands throws some errors now:
( the command !epic works fine)


```
Loading prime gaming data
[WDM] - Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6.96M/6.96M [00:00<00:00, 89.0MB/s]
2023-01-27 13:25:46 ERROR    discord.client Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "//discord_bot.py", line 25, in on_message
    await get_twitch_data.handle_cmd(message=message, games=ALLOWED_GAMES, message_type=MSG_TYPE_TWITCH,
  File "/bot_modules/get_twitch_data.py", line 255, in handle_cmd
    data_json = fetch_data()
  File "/bot_modules/get_twitch_data.py", line 109, in fetch_data
    soup = get_html_data()
  File "/bot_modules/get_twitch_data.py", line 25, in get_html_data
    driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()), options=options)
  File "/usr/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 80, in __init__
    super().__init__(
  File "/usr/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 101, in __init__
    self.service.start()
  File "/usr/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 88, in start
    self._start_process(self.path)
  File "/usr/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 195, in _start_process
    self.process = subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/root/.wdm/drivers/chromedriver/linux64/109.0.5414/chromedriver'


```

**Comment by riggerbh** [comment]
The file "discord_bot.py" in the Folder "Loot-Bot-Main/bot" 

I changed this (start line 55 at the bottom):

    client = TwitchLootBot()
    client.run(TOKEN)

To this:

    intents = discord.Intents.default()
    intents.message_content = True

    client = TwitchLootBot(intents=intents)

    client.run(TOKEN)

It's running for me. I had to set the Privileged Gateway Intents to "ON" in the Discord applications for the bot before I ran this.

**Comment by Falyrion** [comment]
Maintenance of this project is currently on halt. Many web scraping methods might no longer work due to changes in the target websites. Furthermore, discord.py is no longer maintained by its developers, therefor a rewrite of this project using pycord would be necessary.
